cmake_minimum_required(VERSION 3.21)

set(DESTINATION "${TEST_DIR}/SKSE/Plugins")
set(DLL "${TEST_DIR}/fixture.dll")
set(CONFIG "${SOURCE_DIR}/config/ResponsiveCombat.ini")
set(PDB "")
file(MAKE_DIRECTORY "${TEST_DIR}")
file(REMOVE "${DESTINATION}/ResponsiveCombat.ini")
file(WRITE "${DLL}" "test-dll")
include("${SOURCE_DIR}/cmake/Deploy.cmake")
file(READ "${CONFIG}" expected)
file(READ "${DESTINATION}/ResponsiveCombat.ini" actual)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "First deployment did not install the example INI.")
endif()
file(WRITE "${DESTINATION}/ResponsiveCombat.ini" "[General]\nEnabled=false\n")
file(WRITE "${DLL}" "updated-test-dll")
include("${SOURCE_DIR}/cmake/Deploy.cmake")
file(READ "${DESTINATION}/ResponsiveCombat.ini" actual)
file(READ "${DESTINATION}/ResponsiveCombat.dll" deployed)
if(NOT actual STREQUAL "[General]\nEnabled=false\n" OR NOT deployed STREQUAL "updated-test-dll")
    message(FATAL_ERROR "Redeployment must update the DLL and preserve the installed INI.")
endif()
