cmake_minimum_required(VERSION 3.21)

if(NOT EXISTS "${DLL}" OR NOT EXISTS "${CONFIG}" OR NOT DESTINATION)
    message(FATAL_ERROR "Deployment requires a built DLL, example INI, and destination.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY_FILE "${DLL}" "${DESTINATION}/ResponsiveCombat.dll" ONLY_IF_DIFFERENT)
if(PDB)
    file(COPY_FILE "${PDB}" "${DESTINATION}/ResponsiveCombat.pdb" ONLY_IF_DIFFERENT)
endif()
if(NOT EXISTS "${DESTINATION}/ResponsiveCombat.ini")
    file(COPY_FILE "${CONFIG}" "${DESTINATION}/ResponsiveCombat.ini")
endif()
message(STATUS "Deployed ResponsiveCombat to ${DESTINATION}; existing configuration preserved.")
